var mongoose = require('mongoose');
var Schema = mongoose.Schema;

module.exports = mongoose.model('EnergyMeterLog', new Schema({
    energyMeterID: String,
    logID: String,
    Time: Date,
    WattsTotal: Number,
    WattsRPhase: Number,
    WattsYPhase: Number,
    WattsBPhase: Number,
    VARTotal: Number,
    VARRPhase: Number,
    VARYPhase: Number,
    VARBPhase: Number,
    PFAve_Inst: Number,
    PFRPhase: Number,
    PFYPhase: Number,
    PFBPhase: Number,
    VATotal: Number,
    VARPhase: Number,
    VAYPhase: Number,
    VABPhase: Number,
    VryPhase: Number,
    VybPhase: Number,
    VbrPhase: Number,
    VLNAvg: Number,
    VRPhase: Number,
    VYPhase: Number,
    VBPhase: Number,
    CurrentRPhase: Number,
    CurrentYPhase: Number,
    CurrentBPhase: Number,
    Frequnecy: Number,
    WhReceived: Number
}));